<?php
$this->headTitle($this->translate('Front-end'));
?>

<div id="wrapper" class="container_12">

    <h1>Jasi.us Project</h1>
    <p><?php echo $this->translate('Welcome to Jasi.us Project Frontpage area...'); ?></p>
    <p>
        <a href="<?php echo $this->baseUrl('backend'); ?>"><?php echo $this->translate('Go to back-end'); ?></a><?php echo $this->translate(' or '); ?>
        <a href="http://www.jasi.us" target="_blank"><?php echo $this->translate('Visit Jasi.us Project\'s web site'); ?></a>
    </p>

</div>
