<?php
$this->headTitle($this->translate('Front-end'));
?>

<div id="wrapper" class="container_12">

    <h1>Jasius is open source, cloud, document management software.</h1>

    <div class="grid_5 alpha">
    <p><?php echo $this->translate('Welcome to Jasi.us Project Frontpage area...'); ?></p>
    <p>
        <a href="<?php echo $this->baseUrl('backend'); ?>"><?php echo $this->translate('Go to back-end'); ?></a><?php echo $this->translate(' or '); ?><br />
        <a href="http://www.jasi.us" target="_blank"><?php echo $this->translate('Visit Jasi.us Project\'s web site'); ?></a>
    </p>
    </div>

    <div class="grid_2"></div>

    <div class="grid_5 omega">
        <p>
            <strong>CLOUD</strong>
            You can share and manage your document on internet wherever or whenever you want.
        </p>

        <p>
            <strong>ROLE BASE AUTHORIZATION</strong>
            You can share or manage your document with different roles or users.
        </p>

        <p>
            <strong>EASY TO USE</strong>
            Jasi.us is very user friendly software that you can use it without any extra effort.
        </p>
    </div>

</div>
