<?php

/**
 * Model_Entity_Data
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $property_id
 * @property integer $content_id
 * @property decimal $decimalValue
 * @property decimal $floatValue
 * @property integer $integerValue
 * @property date $dateValue
 * @property string $stringValue
 * @property time $timeValue
 * @property timestamp $timestampValue
 * @property boolean $booleanValue
 * @property string $enumValue
 * @property array $arrayValue
 * @property object $objectValue
 * @property blob $blobValue
 * @property clob $clobValue
 * @property gzip $gzipValue
 * @property Model_Entity_Property $Property
 * @property Model_Entity_Content $Content
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Entity_Data extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('jasius_data');
        $this->hasColumn('property_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('content_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('decimalValue', 'decimal', 24, array(
             'type' => 'decimal',
             'scale' => 6,
             'length' => '24',
             ));
        $this->hasColumn('floatValue', 'decimal', 24, array(
             'type' => 'decimal',
             'scale' => 6,
             'length' => '24',
             ));
        $this->hasColumn('integerValue', 'integer', 10, array(
             'type' => 'integer',
             'length' => '10',
             ));
        $this->hasColumn('dateValue', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('stringValue', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('timeValue', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('timestampValue', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('booleanValue', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('enumValue', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('arrayValue', 'array', 10000, array(
             'type' => 'array',
             'length' => '10000',
             ));
        $this->hasColumn('objectValue', 'object', null, array(
             'type' => 'object',
             ));
        $this->hasColumn('blobValue', 'blob', 2147483647, array(
             'type' => 'blob',
             'length' => '2147483647',
             ));
        $this->hasColumn('clobValue', 'clob', 2147483647, array(
             'type' => 'clob',
             'length' => '2147483647',
             ));
        $this->hasColumn('gzipValue', 'gzip', null, array(
             'type' => 'gzip',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Entity_Property as Property', array(
             'local' => 'property_id',
             'foreign' => 'id'));

        $this->hasOne('Model_Entity_Content as Content', array(
             'local' => 'content_id',
             'foreign' => 'id'));

        $softdelete0 = new Doctrine_Template_SoftDelete();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $blameable0 = new Doctrine_Template_Blameable();
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'decimalValue',
              1 => 'integerValue',
              2 => 'floatValue',
              3 => 'dateValue',
              4 => 'timeValue',
              5 => 'timestampValue',
              6 => 'enumValue',
              7 => 'stringValue',
              8 => 'clobValue',
              9 => 'arrayValue',
              10 => 'objectValue',
             ),
             'className' => 'JasiusDataSearch',
             ));
        $this->actAs($softdelete0);
        $this->actAs($timestampable0);
        $this->actAs($blameable0);
        $this->actAs($searchable0);
    }
}