<?php

/**
 * Model_Entity_Data
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $property_id
 * @property integer $content_id
 * @property decimal $numberValue
 * @property string $textValue
 * @property timestamp $timeValue
 * @property Model_Entity_Property $Property
 * @property Model_Entity_Content $Content
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Entity_Data extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('docloud_data');
        $this->hasColumn('property_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('content_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('numberValue', 'decimal', 24, array(
             'type' => 'decimal',
             'scale' => 6,
             'notnull' => true,
             'length' => '24',
             ));
        $this->hasColumn('textValue', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('timeValue', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Entity_Property as Property', array(
             'local' => 'property_id',
             'foreign' => 'id'));

        $this->hasOne('Model_Entity_Content as Content', array(
             'local' => 'content_id',
             'foreign' => 'id'));

        $softdelete0 = new Doctrine_Template_SoftDelete();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $blameable0 = new Doctrine_Template_Blameable();
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'numberValue',
              1 => 'textValue',
              2 => 'timeValue',
             ),
             'className' => 'DocloudDataSearch',
             ));
        $this->actAs($softdelete0);
        $this->actAs($timestampable0);
        $this->actAs($blameable0);
        $this->actAs($searchable0);
    }
}