<?php

/**
 * Model_Entity_Property
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $type_id
 * @property string $title
 * @property enum $dataType
 * @property int $isUnique
 * @property int $isRequire
 * @property string $defaultValue
 * @property object $enum
 * @property integer $weight
 * @property Model_Entity_Type $Type
 * @property Doctrine_Collection $Data
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Entity_Property extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('docloud_property');
        $this->hasColumn('type_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('dataType', 'enum', 9, array(
             'type' => 'enum',
             'length' => 9,
             'values' => 
             array(
              0 => 'integer',
              1 => 'string',
              2 => 'boolean',
              3 => 'enum',
              4 => 'float',
              5 => 'decimal',
              6 => 'array',
              7 => 'object',
              8 => 'blob',
              9 => 'clob',
              10 => 'timestamp',
              11 => 'time',
              12 => 'date',
              13 => 'gzip',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('isUnique', 'int', 1, array(
             'type' => 'int',
             'notnull' => true,
             'length' => '1',
             ));
        $this->hasColumn('isRequire', 'int', 1, array(
             'type' => 'int',
             'notnull' => true,
             'length' => '1',
             ));
        $this->hasColumn('defaultValue', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('enum', 'object', null, array(
             'type' => 'object',
             ));
        $this->hasColumn('weight', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Entity_Type as Type', array(
             'local' => 'type_id',
             'foreign' => 'id'));

        $this->hasMany('Model_Entity_Data as Data', array(
             'local' => 'data_id',
             'foreign' => 'id'));

        $softdelete0 = new Doctrine_Template_SoftDelete();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $blameable0 = new Doctrine_Template_Blameable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             'className' => 'PropertyTranslation',
             'length' => 2,
             ));
        $this->actAs($softdelete0);
        $this->actAs($timestampable0);
        $this->actAs($blameable0);
        $this->actAs($i18n0);
    }
}